name: vchat
description: Advanced Chat App.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #style and design 
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.23.0+1
  google_fonts: ^2.1.0
  pinput: ^1.2.2
  sizer: ^2.0.15

  #architecture
  flutter_riverpod: ^1.0.0
  shared_preferences: ^2.0.8
  dio: ^4.0.3
 

  #firebase 
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0

  #other
  google_sign_in: ^5.2.1
  image_picker: ^0.8.4+4
  googleapis: ^7.0.0
  googleapis_auth: ^1.3.0
  http: ^0.13.4
  path_provider: ^2.0.7
  url_launcher: ^6.0.15
  flutter_secure_storage: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/